repos:
-   hooks:
    -   id: go-build-mod
        name: go-build-mod
        entry: go-build-mod.sh
        files: (\.go$)|(\bgo\.mod$)
        exclude: (^|/)vendor/
        language: script
        description: Run 'cd $(mod_root $FILE); go build -o /dev/null [$ARGS] ./...'
            for each staged .go file
        pass_filenames: true
        require_serial: true
    -   id: go-critic
        name: go-critic
        entry: go-critic.sh
        types:
        - go
        exclude: (^|/)vendor/
        language: script
        description: Run 'gocritic check [$ARGS] $FILE' for each staged .go file
        pass_filenames: true
    -   id: go-mod-tidy
        name: go-mod-tidy
        entry: go-mod-tidy.sh
        files: (\.go$)|(\bgo\.mod$)
        exclude: (^|/)vendor/
        language: script
        description: Run 'cd $(mod_root $FILE); go mod tidy [$ARGS]' for each staged
            .go file
        pass_filenames: true
        require_serial: true
    -   id: golangci-lint-mod
        name: golangci-lint-mod
        entry: golangci-lint-mod.sh
        files: (\.go$)|(\bgo\.mod$)
        exclude: (^|/)vendor/
        language: script
        description: Run 'cd $(mod_root $FILE); golangci-lint run [$ARGS] ./...' for
            each staged .go file
        pass_filenames: true
        require_serial: true
    -   id: go-test-mod
        name: go-test-mod
        entry: go-test-mod.sh
        files: (\.go$)|(\bgo\.mod$)
        exclude: (^|/)vendor/
        language: script
        description: Run 'cd $(mod_root $FILE); go test [$ARGS] ./...' for each staged
            .go file
        pass_filenames: true
        require_serial: true
    -   id: go-vet-mod
        name: go-vet-mod
        entry: go-vet-mod.sh
        files: (\.go$)|(\bgo\.mod$)
        exclude: (^|/)vendor/
        language: script
        description: Run 'cd $(mod_root $FILE); go vet [$ARGS] ./...' for each staged
            .go file
        pass_filenames: true
        require_serial: true
    repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-beta.5
-   hooks:
    -   id: commitizen
        stages:
        - commit-msg
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.35.0
